### ISSUE TITLE
Entity Crash

### ISSUE THREAD

**Issue by Luxzhv** [Skylortrexler/apotheosis#3]
Error caused by breaking non-organic entities (Boats, Fireballs, End Crystals.) with primary fire, causing client only crash, server not effected.
-----------------------------------------------------
Time: 10/2/21, 11:05 AM
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_1690 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1690 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at net.minecraft.class_1657.redirect$zff000$injectedAttack(class_1657.java:2855)
	at net.minecraft.class_1657.method_7324(class_1657.java:1244)
	at net.minecraft.class_636.method_2918(class_636.java:383)
	at net.minecraft.class_310.method_1536(class_310.java:1583)
	at net.minecraft.class_310.method_1508(class_310.java:1897)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1657.redirect$zff000$injectedAttack(class_1657.java:2855)
	at net.minecraft.class_1657.method_7324(class_1657.java:1244)
	at net.minecraft.class_636.method_2918(class_636.java:383)
	at net.minecraft.class_310.method_1536(class_310.java:1583)
	at net.minecraft.class_310.method_1508(class_310.java:1897)

-- Affected level --
Details:
	All players: 1 total; [class_746['Player'/1256, l='ClientLevel', x=-222.20, y=63.00, z=93.50]]
	Chunk stats: 841, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,64,96), Section: (at 0,0,0 in -15,4,6; chunk contains blocks -240,0,96 to -225,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 687 game time, 687 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by skylorbeck** [comment]
Thank you for the report!

**Comment by skylorbeck** [comment]
Can you tell me what you were doing?

**Comment by Luxzhv** [comment]
Just made a boat, placed it in water and punched it once.

**Comment by Luxzhv** [comment]
I made sure to list more things at the top of the report... and there seems to be particular cases where interacting with a boat at all would crash the client, some had the ability of picking said boat back up by lighting it on fire first.

**Comment by skylorbeck** [comment]
Thank you. I think I know exactly whats happening.

**Comment by Luxzhv** [comment]
Woo! I had even rolled back to Geckolib 3.0.12 to see if a newer version was causing a crash, but the crash still occurred. Best of luck, Leaving this open for about an hour or so if you need more information.

**Comment by skylorbeck** [comment]
I'll close it when it's fixed. Please don't close it before that. Thank you!

**Comment by skylorbeck** [comment]
Should be live on curseforge in a few minutes :) cheers!
